version: "3"
services:
  db:
    image: mysql:8.0
    container_name: symfony-login-db
    environment:
    - MYSQL_DATABASE=symfony
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    networks:
    - app-network
    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#    - db_data:/var/lib/mysql
  webserver:
    image: nginx:alpine
    container_name: symfony-login-webserver
    working_dir: /application
    volumes:
    - .:/application
    - ./phpdocker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    networks:
    - app-network

  php-fpm:
    depends_on:
    - db
    build: phpdocker/dev/php-fpm
    container_name: symfony-login-php-fpm
    working_dir: /application
    volumes:
    - .:/application
    networks:
    - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db_data: